version: "3.8"

services:
  postgres-event:
    image: postgres:latest
    environment:
      - POSTGRES_DB=bank_db
      - POSTGRES_USER=pavel
      - POSTGRES_PASSWORD=admin
    ports:
      - "5433:5432"