version: "3.8"

services:
  postgres-event:
    image: postgres:latest
    environment:
      - POSTGRES_DB=event_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5433:5432"