server:
  port: 8081

spring:
  liquibase:
    change-log: classpath:db/master.xml
  datasource:
    url: jdbc:postgresql://localhost:5433/bank_db
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    hikari:
      schema: bank_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS bank_schema
      connection-timeout: 10000

  jpa:
    generate-ddl: false
    open-in-view: false

user-service:
  jwt:
    secret: MyVeryLongAndSecureSecretKeyForJWTTokenSigningThatIsAtLeast64CharactersLongToMeetHS512Requirements123456789
    tokenExpiration: 1m
    refreshTokenExpiration: 30m